version: "3.9"
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-17T01-15-57Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
  spark:
    image: bitnami/spark:3.4
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./:/workspace
