id: payments_v2
domain: finanzas

source:
  path: s3a://raw/payments/2025/09/28/big_sample.csv
  input_format: csv
  options:
    header: true
    inferSchema: true

standardization:
  timezone: America/Bogota
  rename:
    - { from: customerId, to: customer_id }
  casts:
    - { column: amount, to: "decimal(18,2)", on_error: null }
    - { column: payment_date, to: "timestamp", format_hint: "yyyy-MM-dd[ HH:mm:ss]" }
  defaults:
    - { column: currency, value: "CLP" }
  deduplicate:
    key: [payment_id]
    order_by: [updated_at desc]

schema:
  ref: config/datasets/finanzas/payments_v2/schema.json
  mode: strict

quality:
  expectations_ref: config/datasets/finanzas/payments_v2/expectations.yml
  quarantine: s3a://raw/quarantine/payments_v2/

output:
  silver:
    path: s3a://silver/payments_v2/
    format: parquet
    mode: append
    merge_schema: true
    partition_by: [year, month]
