id: payments_v2
domain: finanzas

source:
  path: s3://raw/payments/2025/09/28/big_sample.csv
  input_format: csv
  options:
    header: true
    inferSchema: true

standardization:
  timezone: America/Bogota
  rename:
    - { from: customerId, to: customer_id }
  casts:
    - { column: amount, to: "decimal(18,2)", on_error: null }
    - { column: payment_date, to: "timestamp", format_hint: "yyyy-MM-dd[ HH:mm:ss]" }
  defaults:
    - { column: currency, value: "CLP" }
  deduplicate:
    key: [payment_id]
    order_by: [updated_at desc]

schema:
  ref: config/datasets/finanzas/payments_v2/schema.json
  mode: strict

quality:
  expectations_ref: config/datasets/finanzas/payments_v2/expectations.yml
  quarantine: s3://raw/quarantine/payments_v2/

output:
  silver:
    path: s3://silver/payments_v2/
    format: parquet
    mode: append
    merge_schema: true
    partition_by: [year, month]
    partition_from: payment_date

  # Configuración para Gold layer (Base de datos)
  gold:
    enabled: true
    database_config: "config/database.yml"
    environment: "development"  # default, development, production
    
    # Transformaciones específicas del dataset para Gold layer
    # Remover columnas técnicas antes de escribir a Gold
    exclude_columns: ["_run_id", "_ingestion_ts"]
    
    # Optional: Add business-specific columns
    # add_columns: NO WORKS
    #   - { name: "data_source", value: "payments_system", type: "string" }
    #   - { name: "processed_at", value: "current_timestamp()", type: "timestamp" }
    
    # Reglas de negocio específicas del dataset
    business_rules:
      - { condition: "amount > 0", action: "filter" }
      - { condition: "currency IS NOT NULL", action: "filter" }
      
