id: toy_customers
description: Toy customer churn sample used for multi-cloud smoke tests.
legacy_aliases: {}
layers:
  raw:
    compute:
      engine: spark
      options:
        spark.sql.shuffle.partitions: 1
    io:
      source:
        format: csv
        options:
          header: true
        uris:
          s3: s3://example-raw/toy/customers.csv
          abfss: abfss://example@contoso.dfs.core.windows.net/raw/toy/customers.csv
          gs: gs://example-raw/toy/customers.csv
        local_fallback: samples/toy_customers.csv
  bronze:
    compute:
      engine: spark
    transform:
      steps:
        - name: normalize_columns
          params:
            mappings:
              CUSTOMER_ID: customer_id
              SEGMENT: segment
              STATUS: status
      standardization:
        timestamp_columns:
          - signup_ts
    io:
      sink:
        format: delta
        options:
          checkpointLocation: s3://example-bronze/checkpoints/customers/
        uris:
          s3: s3://example-bronze/tables/customers/
          abfss: abfss://example@contoso.dfs.core.windows.net/bronze/customers/
          gs: gs://example-bronze/tables/customers/
  silver:
    compute:
      engine: spark
    transform:
      steps:
        - name: enrich_with_segments
          params:
            lookup_view: cfg/lookups/segments.csv
      references:
        sql: sql/silver/customers.sql
    dq:
      expectations:
        min_row_count: 10
        expect_columns_to_exist:
          - customer_id
          - signup_ts
    io:
      sink:
        format: delta
        uris:
          s3: s3://example-silver/tables/customers/
          abfss: abfss://example@contoso.dfs.core.windows.net/silver/customers/
          gs: gs://example-silver/tables/customers/
  gold:
    compute:
      engine: spark
    io:
      sink:
        format: delta
        options:
          mergeSchema: true
        uris:
          s3: s3://example-gold/marts/customers/
          abfss: abfss://example@contoso.dfs.core.windows.net/gold/customers/
          gs: gs://example-gold/marts/customers/
