# Schema de pagos v3 (YAML)
# Este schema sigue convenciones tipo JSON Schema simplificado
# consumidas por el generador de DDL del proyecto.

title: payments_v3 schema
description: Schema para pagos v3
type: object

properties:
  payment_id:
    type: string
  customer_id:
    type: string
  amount:
    type: number
  currency:
    type: string
    maxLength: 3
  payment_date:
    type: string
    format: date-time
  status:
    type: string
  method:
    type: string
  quantity:
    type: number
  total_amount:
    type: number

required:
  - payment_id
  - customer_id
  - amount
  - payment_date

uniqueConstraints:
  - name: payments_v3_unique_payment_customer
    columns: ["payment_id", "customer_id"]