# Transformaciones para payments_v3
# Se aplican en la etapa Silver antes de la escritura.

on_error: null

transforms:
  # Normaliza moneda a mayúsculas
  - target_column: currency
    expr: "upper(currency)"
    mode: replace
    type: string

  # Normaliza estado a minúsculas
  - target_column: status
    expr: "lower(status)"
    mode: replace
    type: string

  # Ejemplo de columna derivada (simple)
  - target_column: amount_usd
    expr: "amount"
    mode: create
    type: double
  
  # Ejemplo de columna derivada (compleja)
  - target_column: total_amount
    expr: "amount * quantity"
    mode: create
    type: double

udf:
  # Normalización de IDs (Pandas UDF definida en udf_catalog)
  - target_column: customer_id_norm
    function: normalize_id
    args: ["customer_id"]
    type: string
    mode: create
    on_error: null

  # Sanitizado de currency (trim, espacios, caracteres raros)
  - target_column: currency_norm
    function: sanitize_string
    args: ["currency"]
    type: string
    mode: create
    on_error: null