id: payments_multi
description: Ingesta multi-fuente (archivo local) y salida Gold a DB

sources:
  - type: file
    input_format: jsonl
    path: /mvp/data/s3a-staging/finanzas/payments/raw/

standardization:
  rename:
    - from: id
      to: payment_id
  casts:
    - column: amount
      to: double
    - column: created_at
      to: timestamp
      format_hint: yyyy-MM-dd'T'HH:mm:ss'Z'
  defaults:
    - column: currency
      value: USD
  deduplicate:
    key: [payment_id]
    order_by:
      - created_at desc

select_columns:
  - payment_id
  - amount
  - currency
  - created_at

schema:
  ref: config/datasets/finanzas/payments_v3/schema.yml
  mode: permissive

json_normalization:
  flatten: true

output:
  bronze:
    enabled: true
    path: /mvp/data/output/payments/bronze/
    format: parquet
    mode: overwrite
    compression: snappy
    partition_by: [year, month]
    partition_from: created_at
  silver:
    path: /mvp/data/output/payments/silver/
    format: parquet
    merge_schema: true
    mode: append
    partition_by: [year, month]
    partition_from: created_at
  gold:
    enabled: true
    environment: development
    write_mode: upsert
    upsert_keys: [payment_id]
    table_prefix: fin_
    bucket:
      enabled: false
      path: /mvp/data/output/payments/gold/
      format: parquet
      mode: append
      merge_schema: true
      compression: snappy
      coalesce: 12
      partition_by: [year, month]
      partition_from: created_at

quality:
  expectations_ref: config/datasets/finanzas/payments_v3/expectations.yml
  quarantine: /mvp/data/output/payments/quarantine/

transforms_ref: config/datasets/finanzas/payments_v3/transforms.yml