id: payments_v1

source:
  input_format: csv
  path: s3a://raw/payments/2025/09/26/*.csv
  options:
    header: true
    inferSchema: false

schema:
  ref: config/datasets/finanzas/payments_v1/schema.json
  mode: strict   # strict | warn | permissive

standardization:
  timezone: America/Bogota
  rename:
    - { from: customerId, to: customer_id }
  casts:
    - { column: amount, to: "decimal(18,2)", on_error: null }
    - { column: payment_date, to: "timestamp", format_hint: "yyyy-MM-dd[ HH:mm:ss]", on_error: null }
  defaults:
    - { column: currency, value: "CLP" }
  deduplicate:
    key: [payment_id]
    order_by: [updated_at desc]

quality:
  expectations_ref: config/datasets/finanzas/payments_v1/expectations.yml
  quarantine: s3a://raw/quarantine/payments_v1/

output:
  silver:
    format: parquet          # cambia a "delta" si habilitas Delta Lake
    path: s3a://silver/payments_v1/
    mode: append
    partition_by: [year, month]
    merge_schema: true
