version: 1.0.0
id: payments_v1
owner: finanzas@example.com

source:
  type: file
  path: s3a://raw/payments/2025/09/26/*.csv
  input_format: csv
  options:
    header: true
    delimiter: ","
    encoding: UTF-8

schema:
  ref: schema.json
  mode: strict

standardization:
  timezone: America/Bogota
  rename:
    - { from: customerId, to: customer_id }
  casts:
    - { column: amount, to: "decimal(18,2)", on_error: null }
    - { column: payment_date, to: "timestamp", format_hint: "yyyy-MM-dd[ HH:mm:ss]", on_error: null }
  defaults:
    - { column: currency, value: "CLP" }
  deduplicate:
    key: [payment_id]
    order_by: [updated_at desc]

quality:
  expectations_ref: expectations.yml
  quarantine: s3a://raw/quarantine/payments_v1/

output:
  silver:
    path: s3a://silver/payments_v1/
    format: parquet   # cambia a 'delta' si activas delta-spark
    mode: append
    partition_by: [year, month]
    merge_schema: true
