rules:
  # payment_id con formato p-xxx
  - name: payment_id_formato
    expr: "payment_id RLIKE '^p-\\d{3}$'"
    on_fail: quarantine

  # claves y campos críticos no nulos
  - name: not_nulls
    expr: "payment_id IS NOT NULL AND customer_id IS NOT NULL AND payment_date IS NOT NULL"
    on_fail: quarantine

  # montos válidos
  - name: amount_valido
    expr: "amount IS NOT NULL AND amount > 0"
    on_fail: quarantine

  # currency válida (solo CLP|USD|COP por ejemplo)
  - name: currency_lista
    expr: "currency IN ('CLP','USD','COP')"
    on_fail: drop

  # fechas coherentes (ejemplo: no futuras si no aplica)
  - name: fecha_coherente
    expr: "payment_date <= current_timestamp()"
    on_fail: warn
