rules:
  - name: amount_positive
    expr: "amount IS NOT NULL AND amount >= 0"
    severity: error
    on_fail: quarantine     # quarantine | fail | drop | warn

  - name: currency_valid
    expr: "currency IN ('CLP','USD','COP','MXN')"
    severity: warn
    on_fail: quarantine

  - name: payment_date_window
    expr: "payment_date >= date_sub(current_date(), 3650)"   # ~10 años
    severity: warn
    on_fail: quarantine
