transforms:
  # Construir JSON de device_info desde campos anidados
  - name: device_info
    mode: replace
    expr: "CASE WHEN metadata IS NULL THEN '{}' ELSE to_json(named_struct('user_agent', metadata.user_agent, 'ip_address', metadata.ip_address, 'device_type', device_type)) END"

  # Construir JSON de location_data desde geo_location
  - name: location_data
    mode: replace
    expr: "CASE WHEN geo_location IS NULL THEN '{}' ELSE to_json(named_struct('country', geo_location.country, 'city', geo_location.city, 'latitude', geo_location.latitude, 'longitude', geo_location.longitude)) END"

  # Construir JSON de custom_properties a partir de metadatos disponibles
  - name: custom_properties
    mode: replace
    expr: "CASE WHEN metadata IS NULL THEN '{}' ELSE to_json(named_struct('referrer', metadata.referrer, 'campaign_id', metadata.campaign_id)) END"
