rules:
  # Nivel 1: Validaciones de integridad de datos JSON
  # Nota: _corrupt_record solo existe cuando hay errores de parsing, se omite esta validación

  - name: event_id_format_validation
    expr: "event_id IS NOT NULL AND (event_id RLIKE '^EVT-[0-9]{13}-[A-F0-9]{8}$' OR event_id RLIKE '^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$')"
    on_fail: quarantine
    description: "Event ID debe seguir formato EVT-timestamp-hash o UUID (mayúsculas o minúsculas)"

  - name: event_id_length_validation
    expr: "event_id IS NOT NULL AND (LENGTH(event_id) = 26 OR LENGTH(event_id) = 36)"
    on_fail: quarantine
    description: "Event ID debe tener 26 caracteres (formato EVT) o 36 caracteres (UUID)"

  # Nivel 2: Validaciones de campos críticos
  - name: critical_fields_not_null
    expr: "event_id IS NOT NULL AND user_id IS NOT NULL AND event_type IS NOT NULL"
    on_fail: quarantine
    description: "Campos críticos no pueden ser nulos"

  - name: user_id_format_validation
    expr: "user_id IS NOT NULL AND user_id RLIKE '^CUST-[0-9]+$'"
    on_fail: quarantine
    description: "User ID debe seguir formato CUST-XXXXXX"

  - name: session_id_format_validation
    expr: "session_id IS NULL OR session_id = '' OR session_id RLIKE '^SES-[0-9]{13}-[A-F0-9]{6}$' OR session_id RLIKE '^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$'"
    on_fail: quarantine
    description: "Session ID debe seguir formato SES-timestamp-hash, UUID o estar vacío"

  # Nivel 3: Validaciones de tipos de eventos
  - name: event_type_whitelist
    expr: "event_type IN ('PAGE_VIEW', 'CLICK', 'PURCHASE', 'SIGNUP', 'LOGIN', 'LOGOUT', 'SEARCH', 'ADD_TO_CART', 'CHECKOUT', 'PAYMENT', 'ERROR', 'CUSTOM', 'DOWNLOAD', 'SHARE')"
    on_fail: quarantine
    description: "Tipo de evento debe estar en la lista permitida"

  - name: event_type_not_empty
    expr: "event_type IS NOT NULL AND LENGTH(TRIM(event_type)) > 0"
    on_fail: quarantine
    description: "Tipo de evento no puede estar vacío"

  # Nivel 4: Validaciones temporales complejas
  - name: event_timestamp_not_null
    expr: "event_timestamp IS NOT NULL"
    on_fail: warn
    description: "Timestamp del evento es obligatorio"

  - name: event_timestamp_not_future
    expr: "event_timestamp IS NULL OR event_timestamp <= current_timestamp()"
    on_fail: warn
    description: "Timestamp del evento no puede ser futuro"

  - name: event_timestamp_not_too_old
    expr: "event_timestamp IS NULL OR event_timestamp >= '2023-01-01 00:00:00'"
    on_fail: warn
    description: "Timestamp del evento no debe ser anterior a 2023"

  - name: event_timestamp_reasonable_range
    expr: "event_timestamp >= date_sub(current_timestamp(), 365) AND event_timestamp <= date_add(current_timestamp(), 1)"
    on_fail: warn
    description: "Timestamp debe estar en rango razonable (último año + 1 día)"

  # Nivel 6: Validaciones de datos JSON anidados
  - name: device_info_json_validation
    expr: "device_info IS NULL OR device_info = '{}' OR (device_info LIKE '{%}' AND device_info NOT LIKE '%\"\":%' AND device_info NOT LIKE '%:\"\",%')"
    on_fail: warn
    description: "Device info debe ser JSON válido o vacío"

  - name: location_data_json_validation
    expr: "location_data IS NULL OR location_data = '{}' OR (location_data LIKE '{%}' AND location_data NOT LIKE '%\"\":%' AND location_data NOT LIKE '%:\"\",%')"
    on_fail: warn
    description: "Location data debe ser JSON válido o vacío"

  - name: custom_properties_json_validation
    expr: "custom_properties IS NULL OR custom_properties = '{}' OR (custom_properties LIKE '{%}' AND custom_properties NOT LIKE '%\"\":%' AND custom_properties NOT LIKE '%:\"\",%')"
    on_fail: warn
    description: "Custom properties debe ser JSON válido o vacío"

  # Nivel 7: Validaciones de longitud de campos
  - name: event_id_length_exact
    expr: "LENGTH(event_id) = 26 OR LENGTH(event_id) = 36"
    on_fail: quarantine
    description: "Event ID debe tener 26 caracteres (formato EVT) o 36 caracteres (UUID)"

  - name: session_id_length_validation
    expr: "session_id IS NULL OR session_id = '' OR LENGTH(session_id) = 22 OR LENGTH(session_id) = 36"
    on_fail: quarantine
    description: "Session ID debe tener 22 o 36 caracteres (UUID) o estar vacío"

  - name: device_info_length_limit
    expr: "device_info IS NULL OR LENGTH(device_info) <= 1000"
    on_fail: warn
    description: "Device info no debe exceder 1000 caracteres"

  - name: location_data_length_limit
    expr: "location_data IS NULL OR LENGTH(location_data) <= 500"
    on_fail: warn
    description: "Location data no debe exceder 500 caracteres"

  - name: custom_properties_length_limit
    expr: "custom_properties IS NULL OR LENGTH(custom_properties) <= 2000"
    on_fail: warn
    description: "Custom properties no debe exceder 2000 caracteres"

  - name: error_events_have_details
    expr: "event_type != 'ERROR' OR (event_type = 'ERROR' AND custom_properties IS NOT NULL AND custom_properties != '{}')"
    on_fail: quarantine
    description: "Eventos de error deben tener detalles en custom_properties"

  - name: login_logout_session_consistency
    expr: "event_type NOT IN ('LOGIN', 'LOGOUT') OR (event_type IN ('LOGIN', 'LOGOUT') AND session_id IS NOT NULL AND session_id != '')"
    on_fail: quarantine
    description: "Eventos de login/logout deben tener session_id"

  # Nivel 9: Validaciones de patrones sospechosos
  - name: no_test_data_patterns
    expr: "NOT (event_id LIKE '%TEST%' OR event_id LIKE '%DUMMY%' OR user_id IN (0, 1, 123, 999999999))"
    on_fail: drop
    description: "Detectar y filtrar datos de prueba"

  - name: no_bot_patterns
    expr: "NOT (user_id < 1000 AND event_type = 'PAGE_VIEW' AND session_id IS NULL)"
    on_fail: drop
    description: "Detectar patrones de bots o tráfico automatizado"

  - name: reasonable_event_frequency
    expr: "TRUE"  # Esta validación requiere ventanas temporales complejas
    on_fail: warn
    description: "Frecuencia de eventos debe ser razonable por usuario"

  # Nivel 10: Validaciones de calidad de datos avanzadas
  - name: timestamp_precision_validation
    expr: "event_timestamp IS NULL OR date_format(event_timestamp, 'yyyy-MM-dd HH:mm:ss') IS NOT NULL"
    on_fail: warn
    description: "Timestamp debe ser válido y formateado correctamente"

  - name: consistent_timezone_usage
    expr: "TRUE"  # Asumimos que todos los timestamps están en UTC
    on_fail: warn
    description: "Todos los timestamps deben estar en UTC"

  - name: event_id_uniqueness_pattern
    expr: "event_id IS NOT NULL AND (SUBSTRING(event_id, 5, 13) RLIKE '^[0-9]{13}$' OR event_id RLIKE '^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$')"
    on_fail: quarantine
    description: "Event ID debe tener formato válido (EVT con timestamp o UUID en mayúsculas o minúsculas)"

  # Nivel 11: Validaciones de integridad referencial simulada
  - name: user_id_format_consistency
    expr: "user_id IS NOT NULL AND (user_id RLIKE '^CUST-[0-9]+$' OR CAST(user_id AS STRING) RLIKE '^[1-9][0-9]*$')"
    on_fail: quarantine
    description: "User ID debe seguir formato CUST-XXXXXX o ser entero positivo válido"

  - name: session_user_consistency
    expr: "session_id IS NULL OR session_id = '' OR user_id IS NOT NULL"
    on_fail: warn
    description: "Sessions deben estar asociadas a usuarios válidos"