# Database configuration for PostgreSQL environments
# Configuración exclusiva para PostgreSQL

# Default environment (PostgreSQL local)
default:
  engine: postgresql
  host: localhost
  port: 5432
  database: data_warehouse
  username: postgres
  password: postgres123
  schema: gold
  
  # Connection pool settings
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Development environment (Docker PostgreSQL)
development:
  engine: postgresql
  host: postgres
  port: 5432
  database: data_warehouse
  username: postgres
  password: postgres123
  schema: gold
  
  # Connection pool settings
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600

# Production environment (External PostgreSQL)
production:
  engine: postgresql
  host: ${DB_HOST}
  port: ${DB_PORT}
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  schema: ${DB_SCHEMA}
  
  # Connection pool settings
  pool_size: 20
  max_overflow: 40
  pool_timeout: 30
  pool_recycle: 3600

# Global database settings
settings:
  # Table creation settings
  create_tables_if_not_exists: true

# Table settings for Gold layer
table_settings:
  # Table naming configuration
  table_prefix: ""              # Prefix for table names (empty by default)
  table_suffix: ""              # Suffix for table names (empty by default)
  
  # Schema versioning
  version_format: "%Y%m%d_%H%M%S"  # Format for schema version timestamps
  schema_versioning: true       # Enable schema versioning
  auto_migrate: false          # Set to true for automatic schema migrations
  
  # Write behavior
  default_write_mode: "overwrite"  # Default mode for writing data (append/overwrite)
  upsert_keys: [] # Default upsert keys for MERGE/UPSERT operations (empty = disabled)
  
  # Global transformations (can be overridden by dataset-specific config)
  default_transformations:
    exclude_columns: ["_run_id", "_ingestion_ts"]  # Default technical columns to exclude