# Plantilla de Workflow Template para ejecutar la cadena completa en Dataproc
id: prodi-layered-pipeline
placement:
  managed_cluster:
    cluster_name: prodi-etl-managed
    config:
      gce_cluster_config:
        zone_uri: us-central1-a
      software_config:
        image_version: 2.1-debian11
jobs:
  - step_id: raw
    pyspark_job:
      main_python_file_uri: gs://datalake-artifacts/scripts/prodi_dataproc_entry.py
      python_file_uris:
        - gs://datalake-artifacts/libs/prodi-1.4.0-py3-none-any.whl
      args:
        - --layer
        - raw
        - --config
        - gs://datalake-artifacts/cfg/run/raw.yml
  - step_id: bronze
    prerequisite_step_ids: [raw]
    pyspark_job:
      main_python_file_uri: gs://datalake-artifacts/scripts/prodi_dataproc_entry.py
      python_file_uris:
        - gs://datalake-artifacts/libs/prodi-1.4.0-py3-none-any.whl
      args:
        - --layer
        - bronze
        - --config
        - gs://datalake-artifacts/cfg/run/bronze.yml
  - step_id: silver
    prerequisite_step_ids: [bronze]
    pyspark_job:
      main_python_file_uri: gs://datalake-artifacts/scripts/prodi_dataproc_entry.py
      python_file_uris:
        - gs://datalake-artifacts/libs/prodi-1.4.0-py3-none-any.whl
      args:
        - --layer
        - silver
        - --config
        - gs://datalake-artifacts/cfg/run/silver.yml
  - step_id: gold
    prerequisite_step_ids: [silver]
    pyspark_job:
      main_python_file_uri: gs://datalake-artifacts/scripts/prodi_dataproc_entry.py
      python_file_uris:
        - gs://datalake-artifacts/libs/prodi-1.4.0-py3-none-any.whl
      args:
        - --layer
        - gold
        - --config
        - gs://datalake-artifacts/cfg/run/gold.yml
