project: mvp-config-driven
environment: prod
platform: gcp
layer: bronze
datasets:
  - name: customers_bronze
    layer: bronze
    source:
      type: storage
      format: parquet
      uri: "gs://mvp-raw/customers/_landing/"
      backend: gcp
    transform:
      sql:
        - "SELECT *, current_timestamp() AS _ingestion_ts FROM _src"
    sink:
      type: storage
      format: parquet
      uri: "gs://mvp-bronze/customers/"
      backend: gcp
    incremental:
      mode: append
