project: mvp-config-driven
environment: prod
platform: gcp
layer: silver
datasets:
  - name: customers_silver
    layer: silver
    source:
      type: storage
      format: parquet
      uri: "gs://mvp-bronze/customers/"
      backend: gcp
    transform:
      sql:
        - "SELECT id, name, email, country, CAST(amount AS DOUBLE) AS amount FROM _src"
    sink:
      type: storage
      format: parquet
      uri: "gs://mvp-silver/customers/"
      backend: gcp
    incremental:
      mode: append
