# Dataset: payments_db_only
# Ingesta exclusiva desde base de datos (JDBC) y escritura Gold en bucket

id: payments_db_only
description: "Pagos - Ingesta exclusiva JDBC (DB-only)."

sources:
  - type: jdbc
    jdbc:
      url: jdbc:postgresql://postgres:5432/data_warehouse
      table: finanzas.payments_db_only_src
      user: postgres
      password: postgres123
      driver: org.postgresql.Driver

# Estandarización previa a particionado, calidad y escritura
standardization:
  timezone: America/Bogota
  casts:
    - { column: amount, to: "decimal(18,2)", on_error: null }
    - { column: payment_date, to: timestamp, format_hint: "yyyy-MM-dd[ HH:mm:ss]", on_error: null }
  defaults:
    - { column: currency, value: "USD" }
    - { column: customer_id, value: "CUST-DB" }
    - { column: status, value: "completed" }
    - { column: method, value: "card" }
  deduplicate:
    key: [payment_id, customer_id]
    order_by: [payment_date desc]

# Proyección explícita de columnas útiles
select_columns:
  - id
  - customer_id
  - amount
  - currency
  - created_at
  - payment_id
  - payment_date
  - status
  - method
  - quantity
  - total_amount

# Referencia de schema y modo de aplicación
schema:
  ref: config/datasets/finanzas/payments_db_only/schema.yml
  mode: permissive

# Transformaciones declarativas (SQL y UDFs)
transforms_ref: config/datasets/finanzas/payments_db_only/transforms.yml

quality:
  expectations_ref: config/datasets/finanzas/payments_db_only/expectations.yml
  quarantine: s3://raw/quarantine/payments_db_only/

# Capas de salida
output:
  silver:
    format: parquet
    path:  s3://silver/payments_db_only/
    partition_by: ["year", "month"]
    partition_from: payment_date
    merge_schema: true
    mode: overwrite_dynamic
    compression: snappy
  gold:
    enabled: false  # Deshabilita Gold DB; usamos bucket
    exclude_columns: ["_run_id", "_ingestion_ts", "id", "created_at"]
    add_columns:
      - { name: "data_source", value: "payments_db_only", type: "string" }
      - { name: "processed_at", value: "current_timestamp()", type: "timestamp" }
    bucket:
      enabled: true
      path: s3://gold/payments_db_only/
      format: parquet
      mode: append
      partition_by: ["year", "month"]
      partition_from: payment_date
      merge_schema: true
      compression: snappy