# Schema de pagos DB-only (YAML)
# Basado en convenciones del proyecto (JSON Schema simplificado)

title: payments_db_only schema
description: Schema para pagos con ingesta exclusiva JDBC
type: object

properties:
  payment_id:
    type: string
  customer_id:
    type: string
  amount:
    type: number
  currency:
    type: string
    maxLength: 3
  payment_date:
    type: string
    format: date-time
  status:
    type: string
  method:
    type: string
  quantity:
    type: number
  total_amount:
    type: number

required:
  - payment_id
  - customer_id
  - amount
  - payment_date

uniqueConstraints:
  - name: payments_db_only_unique_payment_customer
    columns: ["payment_id", "customer_id"]