# Transformaciones para payments_db_only
# Aplicadas en Silver antes de la escritura

on_error: null

transforms:
  # Normaliza moneda a mayúsculas
  - target_column: currency
    expr: "upper(currency)"
    mode: replace
    type: string

  # Normaliza estado a minúsculas
  - target_column: status
    expr: "lower(status)"
    mode: replace
    type: string

  # Unifica payment_id (usa id si falta)
  - target_column: payment_id
    expr: "coalesce(payment_id, cast(id as string))"
    mode: replace
    type: string

  # Unifica payment_date (usa created_at si falta)
  - target_column: payment_date
    expr: "coalesce(payment_date, to_timestamp(created_at))"
    mode: replace
    type: timestamp

  # Derivados
  - target_column: amount_usd
    expr: "amount"
    mode: create
    type: double

  - target_column: total_amount
    expr: "amount * quantity"
    mode: create
    type: double

udf:
  - target_column: customer_id_norm
    function: normalize_id
    args: ["customer_id"]
    type: string
    mode: create
    on_error: null

  - target_column: currency_norm
    function: sanitize_string
    args: ["currency"]
    type: string
    mode: create
    on_error: null