name: CI — Validate & Lint

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  validate-cfg:
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      PRODI_FORCE_DRY_RUN: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e lib/datacore || (cd lib/datacore && pip install -e .)
          pip install pyyaml typer "pydantic==2.*" fsspec adlfs gcsfs s3fs ruamel.yaml ruff

      - name: Ruff (lint no-blocking)
        run: |
          ruff check lib/datacore || true

      - name: Validate YAML templates
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob

          files=(templates/**/cfg/*.yml cfg/**/*.yml)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No se encontraron YAMLs de cfg; revisa templates/**/cfg/*.yml o cfg/**/*.yml"
            exit 1
          fi

          for f in "${files[@]}"; do
            echo "::group::prodi validate -c $f"
            prodi validate -c "$f"
            echo "::endgroup::"
          done
