name: CI

on:
  push:
    branches: ["refactor/multicloud-v1"]
  pull_request:
    branches: ["main", "refactor/multicloud-v1"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check datacore tests
          black --check datacore tests
      - name: Tests
        run: pytest
